[project]
name = "omarchy-intent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Simon Cossar", email = "scossar3@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.5.9",
    "ipython>=9.17.1",
    "pyyaml>=6.0.3",
    "rich>=15.0.0",
    "tensorflow>=2.21.0",
]

[project.scripts]
omarchy-intent = "omarchy_intent:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
